### PR TITLE
Send request accepted campaign to student in signal

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/api/signals/student.py` line 130 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O24y0jMDOBX8feurzn9:-O24y0jMDOBX8feurznA:b-25efyj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/23328a6e63d3b0b3fa863779739d719ebf266970/src/api/signals/student.py#L130)):*
> ```Python
>                     ],
>                     to_addresses=[instance.new_user.email],
>                     personalization_values={
> ```


Change this data binding to just be "@LOGIN_URL@".

You should create this setting [here](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/fdaf14f13ed247b0b119270ab8c1081a4bfb338e/settings.py#L271)
```py
PAGE_STUDENT_LOGIN = f"{SERVICE_SITE_URL}/login/student"
```
Then add this personalization value
```py
"LOGIN_URL" = f"{settings.PAGE_STUDENT_LOGIN}/{instance.class_field}"
```

**Review by SKairinos — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`src/api/signals/student.py` line 130 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O24y0jMDOBX8feurzn9:-O25E_DA33W1V-_sQ0T6:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/23328a6e63d3b0b3fa863779739d719ebf266970/src/api/signals/student.py#L130)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>


Change this data binding to just be "@LOGIN_URL@".

You should create this setting [here](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/fdaf14f13ed247b0b119270ab8c1081a4bfb338e/settings.py#L271)
```py
PAGE_STUDENT_LOGIN = f"{SERVICE_SITE_URL}/login/student"
```
Then add this personalization value
```py
"LOGIN_URL" = f"{settings.PAGE_STUDENT_LOGIN}/{instance.class_field}"
```
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/signals/student.py` line 125 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O25FkPY91sBjcoTn75P:-O25FkPY91sBjcoTn75Q:b-kkoehx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/80c0d4c6076a9210a8122e7015113e62546592a8/src/api/signals/student.py#L125)):*
> ```Python
>             else:
>                 # TODO: user student.user.email_user() in new schema.
>                 access_code = previous_pending_class_request.access_code
> ```

for the sake of readability please change to
```py
instance.class_field.access_code
```
When sending the "accepted into class" notification, we should reference the class they are now a part of.
___
*[`src/api/signals/student.py` line 133 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O25FteZ2sxrzD4gTTSs:-O25FteZ2sxrzD4gTTSt:b-1ftg7q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/80c0d4c6076a9210a8122e7015113e62546592a8/src/api/signals/student.py#L133)):*
> ```Python
>                     personalization_values={
>                         "SCHOOL_NAME": (
>                             previous_pending_class_request.teacher.school.name
> ```

for the sake of readability please change to
```py
instance.class_field.teacher.school.name
```
When sending the "accepted into class" notification, we should reference the class they are now a part of.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/signals/student.py` line 125 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O25FkPY91sBjcoTn75P:-O25GaI628dS4ohXjTMU:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/80c0d4c6076a9210a8122e7015113e62546592a8/src/api/signals/student.py#L125)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

for the sake of readability please change to
```py
instance.class_field.access_code
```
When sending the "accepted into class" notification, we should reference the class they are now a part of.
</blockquote></details>

Done.
___
*[`src/api/signals/student.py` line 133 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356#-O25FteZ2sxrzD4gTTSs:-O25GabD3nblqDWgcRhL:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/80c0d4c6076a9210a8122e7015113e62546592a8/src/api/signals/student.py#L133)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

for the sake of readability please change to
```py
instance.class_field.teacher.school.name
```
When sending the "accepted into class" notification, we should reference the class they are now a part of.
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/356)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
