### PR TITLE
Send triggered emails

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: 0 of 16 files reviewed, 1 unresolved discussion

___
*[`Pipfile` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vA3k2AJGCFm0zEW2N:-O-vA3k2AJGCFm0zEW2O:bnbocvi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/01d535a00c5900b11c539233161ae9bc86676ff3/Pipfile#L26)):*
> ```TOML
> 
> [packages]
> codeforlife = {ref = "send_triggered_emails", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

install new version

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: 0 of 16 files reviewed, 2 unresolved discussions

___
*[`src/api/serializers/user.py` line 141 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vBEVJBv0B1h6qWEUG:-O-vBEVJBv0B1h6qWEUH:b-mz9yi5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/01d535a00c5900b11c539233161ae9bc86676ff3/src/api/serializers/user.py#L141)):*
> ```Python
>             independent_user.add_contact_to_dot_digital()
> 
>         verify_email_address_link = settings.SERVICE_BASE_URL + reverse(
> ```

use settings.SERVICE_API_URL

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: 0 of 16 files reviewed, 3 unresolved discussions

___
*[`src/api/signals/school_teacher_invitation.py` line 19 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vCrt-99xC--0v6YGv:-O-vCrt-99xC--0v6YGw:b-3ps7vp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/9de0cf1f0e44b5837e440b79e5791e50096c4b18/src/api/signals/school_teacher_invitation.py#L19)):*
> ```Python
> 
> 
> @receiver(post_save_signal, sender=SchoolTeacherInvitation)
> ```

use signals.post_save

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: 0 of 16 files reviewed, 4 unresolved discussions

___
*[`src/api/signals/student_test.py` line 34 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vFcYL-7gFWWWfSAs8:-O-vFcYL-7gFWWWfSAs9:b-hz7tch) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/9de0cf1f0e44b5837e440b79e5791e50096c4b18/src/api/signals/student_test.py#L34)):*
> ```Python
>     @patch("src.api.signals.student.send_mail")
>     def test_post_save(self, send_mail: Mock):
>         """Releasing a student from a class sends them an email."""
> ```

sends teacher and student an email

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: 0 of 16 files reviewed, 5 unresolved discussions

___
*[`src/api/signals/user.py` line 141 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vH_kn3FwFt37TDiVT:-O-vH_kn3FwFt37TDiVU:b-mrn4uh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/9de0cf1f0e44b5837e440b79e5791e50096c4b18/src/api/signals/user.py#L141)):*
> ```Python
>             )
>     # TODO: remove in new schema
>     elif instance.email == "" and post_save.previous_values_are_unequal(
> ```

handle independent joining class
___
*[`src/api/views/user.py` line 108 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O-vINItEGQFARptHwIa:-O-vINItEGQFARptHwIb:b28e4pn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/9de0cf1f0e44b5837e440b79e5791e50096c4b18/src/api/views/user.py#L108)):*
> ```Python
>         return queryset
> 
>     def create(self, request, *args, **kwargs):
> ```

check create teacher

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, 1 of 1 files at r2, 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/signals/school_teacher_invitation.py` line 39 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09PdMaD6_KjQxrMAVj:-O09PdMaD6_KjQxrMAVk:b-yp64kw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/school_teacher_invitation.py#L39)):*
> ```Python
>             personalization_values={
>                 "SCHOOL_NAME": instance.school.name,
>                 "REGISTRATION_LINK": settings.PAGE_REGISTER,
> ```

Not sure this link is the right one, it needs to work in the same way as the old system where the the link contains an email verification token: https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/teacher/dashboard.py#L170
___
*[`src/api/signals/school_teacher_invitation.py` line 50 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09PufY4uePzePE33W9:-O09PufY4uePzePE33WA:b-cacw1g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/school_teacher_invitation.py#L50)):*
> ```Python
>             personalization_values={
>                 "SCHOOL_NAME": instance.school.name,
>                 "REGISTRATION_LINK": settings.PAGE_REGISTER,
> ```

Same here: https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/teacher/dashboard.py#L170
___
*[`src/api/signals/student.py` line 115 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09SgYF9aYR9pfgzQc0:-O09SgYF9aYR9pfgzQc1:b-c5702m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/student.py#L115)):*
> ```Python
>                     to_addresses=[instance.new_user.email],
>                     personalization_values={
>                         "SCHOOL_NAME": (
> ```

SCHOOL_CLUB_NAME in the DD template

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-:-O09rhKQ2y2rETGVfZMQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/api/signals/school_teacher_invitation.py` line 39 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09PdMaD6_KjQxrMAVj:-O09p_jxDWNSjRmy7DPv:bbftj56) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/school_teacher_invitation.py#L39)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not sure this link is the right one, it needs to work in the same way as the old system where the the link contains an email verification token: https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/teacher/dashboard.py#L170
</blockquote></details>

Done. We should reassess this flow. Teacher should be able to leave their current school.
___
*[`src/api/signals/school_teacher_invitation.py` line 50 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09PufY4uePzePE33W9:-O09paad15Sti7vQNeDz:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/school_teacher_invitation.py#L50)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same here: https://github.com/ocadotechnology/codeforlife-portal/blob/master/portal/views/teacher/dashboard.py#L170
</blockquote></details>

Done.
___
*[`src/api/signals/student.py` line 115 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09SgYF9aYR9pfgzQc0:-O09oCza78AC7CL-FNc8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/student.py#L115)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

SCHOOL_CLUB_NAME in the DD template
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348)* status: all files reviewed, 1 unresolved discussion

___
*[`src/api/signals/school_teacher_invitation.py` line 39 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/348#-O09PdMaD6_KjQxrMAVj:-O09rtcbBH5C1HsVj4xk:bn35euq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/06757a6afef5a65673894d260ca53da862466881/src/api/signals/school_teacher_invitation.py#L39)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Done. We should reassess this flow. Teacher should be able to leave their current school.
</blockquote></details>

Teacher can if not admin

**Pull request merged**
