### PR TITLE
Convert to backend repo

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331)* status: 0 of 102 files reviewed, 2 unresolved discussions

___
*[`Pipfile` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331#-NznJpQ414Ql33Cw18Gq:-NznJpQ414Ql33Cw18Gr:bouza55) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/e562dfe4ac8b90460484d8130b96af4cb16268e7/Pipfile#L26)):*
> ```TOML
> 
> [packages]
> codeforlife = {ref = "convert_to_backend_repo", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

install new py package
___
*[`Pipfile` line 35 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331#-NznJrgc-pmYVn8oKDl6:-NznJrgc-pmYVn8oKDl7:bouza55) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/e562dfe4ac8b90460484d8130b96af4cb16268e7/Pipfile#L35)):*
> ```TOML
> 
> [dev-packages]
> codeforlife = {ref = "convert_to_backend_repo", git = "https://github.com/ocadotechnology/codeforlife-package-python.git", extras = ["dev"]}
> ```

install new py package

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331)* status: all files reviewed, 4 unresolved discussions (waiting on @faucomte97)

___
*[`.devcontainer.json` line 25 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331#-NznUvFA6gvsZlY5YXSa:-NznZKjf8wnT19WP7jrt:b-d30scq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/cf7f22ba07ff5039bf62071d2e3f121a1320c1bf/.devcontainer.json#L25)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

so that you can still run/debug the frontend. The FE repo is mounted in the BE devcontainer so you can still have access to it for E2E and what not. Therefore, I added all the extensions the FE needs 
___
*[`src/service/urls.py` line 28 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331#-NznYktx2aLLv_z_WE6G:-NznZnZ6Alz5RbTwmxDO:bp4kraf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/cf7f22ba07ff5039bf62071d2e3f121a1320c1bf/src/service/urls.py#L28)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This might be what is causing the error. RR's URLs are linked with the old portal's and therefore with `home`.
</blockquote></details>

probably, yes, makes sense. let's make a separate task to resolve this.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331)* status: all files reviewed, 2 unresolved discussions

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/331#-:-NznbP-WC4QuWmKKstZX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions

**Pull request merged**
