### PR TITLE
Delete school

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 21 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`src/api/views/school.py` line 38 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350#-O09tRw-01AFPMtVyZ3r:-O09tRw-01AFPMtVyZ3s:bdwq6wm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/160e5adddce8610581ca052e687a740f30c227d4/src/api/views/school.py#L38)):*
> ```Python
> 
>         for klass in Class.objects.filter(teacher__school=school):
>             for student_user in StudentUser.objects.filter(
> ```

Is there a worry that this might be a really long request to complete? Eg, if the school has 20 classes each with 30 studens, or something?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/api/views/school.py` line 38 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350#-O09tRw-01AFPMtVyZ3r:-O0DgkfB8qOwoAzFWwiz:b-yu9055) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/160e5adddce8610581ca052e687a740f30c227d4/src/api/views/school.py#L38)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is there a worry that this might be a really long request to complete? Eg, if the school has 20 classes each with 30 studens, or something?
</blockquote></details>

Yes, lol. But there's nothing we can do to fully solve this problem since:
1. the username field is unique per user
2. We cannot do bulk updates since we don't use PostgreSQL

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`src/api/views/school.py` line 38 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350#-O09tRw-01AFPMtVyZ3r:-O0DliCe445V_294M_eL:bb7k6fe) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/160e5adddce8610581ca052e687a740f30c227d4/src/api/views/school.py#L38)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

Will be solved in new schema
</blockquote></details>

lol.

**Review by faucomte97 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350#-:-O0Dlkqk0rdeACYcQHoZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/api/views/school.py` line 38 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/350#-O09tRw-01AFPMtVyZ3r:-O0Dlvld4rw0nFbbzNld:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/160e5adddce8610581ca052e687a740f30c227d4/src/api/views/school.py#L38)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

lol.
</blockquote></details>

Done.

**Pull request merged**
