### PR TITLE
Create cron job endpoints for anonymisation warnings

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`src/api/views/user.py` line 347 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SPk1BmVYr4HTZbGD:-O37SPk1BmVYr4HTZbGE:bgkkljh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L347)):*
> ```Python
>         return Response()
> 
>     def _get_inactive_users(self, days: int, same_day: bool):
> ```

no need for same_day arg. always True

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user.py` line 384 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SVvn0czBdJehJXGY:-O37SVvn0czBdJehJXGZ:bko3t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L384)):*
> ```Python
>         )
> 
>         return teacher_queryset, independent_student_queryset
> ```

just return user_queryset directly



_Code quote:_
```Python
        teacher_queryset = user_queryset.filter(
            new_teacher__isnull=False,
            new_student__isnull=True,
        )
        independent_student_queryset = user_queryset.filter(
            new_teacher__isnull=True,
            new_student__class_field__isnull=True,
        )

        return teacher_queryset, independent_student_queryset
```

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user.py` line 434 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SdnE9tH7YkDEPesm:-O37SdnE9tH7YkDEPesn:b2vj7d2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L434)):*
> ```Python
>         haven't been active in a while.
>         """
>         return self._send_verify_email_reminder(
> ```

wrong helper
___
*[`src/api/views/user.py` line 444 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SfIb5EzAOjFJ18B5:-O37SfIb5EzAOjFJ18B6:b2vj7d2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L444)):*
> ```Python
>         haven't been active in a while.
>         """
>         return self._send_verify_email_reminder(
> ```

wrong helper
___
*[`src/api/views/user.py` line 455 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37Sfps-ClYdvdBiQNb:-O37Sfps-ClYdvdBiQNc:b2vj7d2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L455)):*
> ```Python
>         haven't been active in a while.
>         """
>         return self._send_verify_email_reminder(
> ```

wrong helper

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user.py` line 384 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SVvn0czBdJehJXGY:-O3CGKCl75yYahxfVgwa:b-2m5ai5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L384)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just return user_queryset directly
</blockquote></details>

not exactly. just delete `teacher_queryset` and `independent_student_queryset` entirely and directly return`user_queryset`
___
*[`src/api/views/user_test.py` line 747 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3CK9eUB93YkwOw1g8K:-O3CK9eUB93YkwOw1g8L:b363tlr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/4ac06c64f20ca8e76c94e603a8e550835f077bec/src/api/views/user_test.py#L747)):*
> ```Python
>         )
> 
>     def _test_send_inactivity_reminder(
> ```

you don't call this helper anywhere. need to create tests for each reminder. each test should call this helper

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/views/user.py` line 347 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SPk1BmVYr4HTZbGD:-O37kQH167iitgTuHO32:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L347)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

no need for same_day arg. always True
</blockquote></details>

Done.
___
*[`src/api/views/user.py` line 384 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SVvn0czBdJehJXGY:-O37kVtI0BpFLo-iTc_7:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L384)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

just return user_queryset directly
</blockquote></details>

Done.
___
*[`src/api/views/user.py` line 434 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SdnE9tH7YkDEPesm:-O37kdtEAiQz0lg87XDT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L434)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

wrong helper
</blockquote></details>

Done.
___
*[`src/api/views/user.py` line 444 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37SfIb5EzAOjFJ18B5:-O37ke9t6E9bY-TzUQ1Q:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L444)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

wrong helper
</blockquote></details>

Done.
___
*[`src/api/views/user.py` line 455 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O37Sfps-ClYdvdBiQNb:-O37keQs0o29k-W4a5Fo:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/1096c70cf5b0fb09d4a78d6b731749f1036e465d/src/api/views/user.py#L455)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

wrong helper
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
let's figure out why the tests are failing

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-:-O3fYevr5LhihOtUe5Rg:b-zc2cta)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3fZ68u39nC-L-zt6tC:bnn1mr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
> ```Python
>             assert indy_users
> 
>             for teacher_user in teacher_users:
> ```

simplify to TeacherUser.objects.update(date_joined=date_joined)
___
*[`src/api/views/user_test.py` line 765 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZEP81gMecHwb_riA:-O3fZEP81gMecHwb_riB:bqiryz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L765)):*
> ```Python
>                 teacher_user.save()
> 
>             for indy_user in indy_users:
> ```

simplify to IndependentUser.objects.update(date_joined=date_joined)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3fZLkv9qHrP6Zrw3Rw:b-kugvac) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

simplify to TeacherUser.objects.update(date_joined=date_joined)
</blockquote></details>

make sure to do this before you get the list of teacher users
___
*[`src/api/views/user_test.py` line 765 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZEP81gMecHwb_riA:-O3fZVTsDGBkmJXW3HVZ:bm0s080) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L765)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

simplify to IndependentUser.objects.update(date_joined=date_joined)
</blockquote></details>

make sure to do this before you get the list of indy  users

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3hWyaL5Ao8BxudBZWp:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make sure to do this before you get the list of teacher users
</blockquote></details>

Done.
___
*[`src/api/views/user_test.py` line 765 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZEP81gMecHwb_riA:-O3hWyt57LPUEFND8BEl:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L765)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

make sure to do this before you get the list of indy  users
</blockquote></details>

Done.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3mmT4LCSQnOvgW_VFF:b-ilxxje) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you need to do this before you get the list of teacher users
___
*[`src/api/views/user_test.py` line 765 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZEP81gMecHwb_riA:-O3mmaaG4JERvwKRWpsh:blt4o1i) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L765)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you need to do this before you get the list of indy users

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3mn02f90_gnRFD0AdD:b-4dmcfo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

you need to do this before you get the list of teacher users
</blockquote></details>

Why? We don't do that in the other helper for the verification reminders :thinking:

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3mnS52Bjg67GltZz4J:b39u2yf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why? We don't do that in the other helper for the verification reminders :thinking:
</blockquote></details>

so that you list the latest data. here you've update the data after caching it so the cache is immediately outdated.

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3mnrDV1NRLeG4S_jda:bu9y4s0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

so that you list the latest data. here you've update the data after caching it so the cache is immediately outdated.
</blockquote></details>

not sure why we're not doing it other test. maybe should be done there too

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`src/api/views/user_test.py` line 761 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZ68u39nC-L-zt6tB:-O3mocOLCXxsbtRY4NWn:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L761)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

not sure why we're not doing it other test. maybe should be done there too
</blockquote></details>

Done.
___
*[`src/api/views/user_test.py` line 765 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358#-O3fZEP81gMecHwb_riA:-O3mocnR2AAkVNWkK2DJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-backend/blob/5ddc402f840968e366a25d667e7938b28181c495/src/api/views/user_test.py#L765)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

you need to do this before you get the list of indy users
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-backend/358)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
